export const DUMMY_CHATS = [
	{
		_id: 1,
		name: 'John Doe',
		lastMessage: 'Hello, how are you?',
		time: '10:00',
		unread: 0,
		avatar: 'https://i.pravatar.cc/300?img=1',
		members: ['1', '2'],
	},
	{
		_id: 2,
		name: 'Jane Smith',
		lastMessage: 'Good morning!',
		time: '9:30',
		unread: 1,
		avatar: 'https://i.pravatar.cc/300?img=2',
		members: ['1', '3'],
	},
	{
		_id: 3,
		name: 'Bob Johnson',
		lastMessage: "Hey, what's up?",
		time: '8:30',
		unread: 2,
		avatar: 'https://i.pravatar.cc/300?img=3',
		members: ['1', '4'],
	},
	{
		_id: 4,
		name: 'Samantha Brown',
		lastMessage: 'I see what you did there',
		time: '9:00',
		unread: 1,
		avatar: 'https://i.pravatar.cc/300?img=4',
		members: ['1', '5'],
	},
	{
		_id: 5,
		name: 'Michael Ross',
		lastMessage: "I'm taking a break",
		time: '9:30',
		unread: 0,
		avatar: 'https://i.pravatar.cc/300?img=5',
		members: ['1', '6'],
	},
	{
		_id: 6,
		name: 'Emma Wilson',
		lastMessage: "Hey guys, I'm home!",
		time: '9:45',
		unread: 2,
		avatar: 'https://i.pravatar.cc/300?img=6',
		members: ['1', '7'],
	},
	{
		_id: 7,
		name: 'Kyle Davis',
		lastMessage: "I'll catch you later",
		time: '10:00',
		unread: 0,
		avatar: 'https://i.pravatar.cc/300?img=7',
		members: ['1', '8'],
	},
	{
		_id: 8,
		name: 'Jessica Lee',
		lastMessage: 'I love you guys!',
		time: '9:30',
		unread: 3,
		avatar: 'https://i.pravatar.cc/300?img=8',
		members: ['1', '9'],
	},
	{
		_id: 9,
		name: 'Alexander Garcia',
		lastMessage: "I'm done for the day",
		time: '9:00',
		unread: 1,
		avatar: 'https://i.pravatar.cc/300?img=9',
		members: ['1', '10'],
	},
	{
		_id: 10,
		name: 'David Lee',
		lastMessage: "I'm back",
		time: '9:45',
		unread: 0,
		avatar: 'https://i.pravatar.cc/300?img=10',
		members: ['1', '1'],
	},
];
